version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=<DB_SERVER>;Database=<DB_NAME>;User Id=<USER>;Password=<PASSWORD>;
